# Generated by Django 6.0.7 on 2026-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('EMAIL_VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset'), ('LOGIN_2FA', 'Login 2FA')], max_length=30),
        ),
    ]
