# Generated by Django 6.0.7 on 2026-08-05 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_otp_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'code', 'purpose'], name='authenticat_email_a2b318_idx'),
        ),
    ]
