# Generated by Django 6.0.7 on 2026-07-25 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='browser',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='device',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='threat_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['threat_score'], name='history_log_threat__5aeacd_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['created_at'], name='history_log_created_c049f8_idx'),
        ),
    ]
