# Generated by Django 6.0.7 on 2026-07-18 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.MinLengthValidator(64), django.core.validators.MaxLengthValidator(64)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('SUSPICIOUS', 'Suspicious'), ('MALICIOUS', 'Malicious')], default='PENDING', max_length=20)),
                ('malware_family', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_fil_user_id_4449ca_idx'), models.Index(fields=['file_hash'], name='scanner_fil_file_ha_97ed18_idx'), models.Index(fields=['status'], name='scanner_fil_status_50c9d0_idx')],
            },
        ),
    ]
