# Generated by Django 6.0.7 on 2026-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filescan',
            name='extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='filescan',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filescan',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
