# Generated by Django 6.0.7 on 2026-08-03 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_filescan_extension_filescan_file_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('cleaned_file', models.FileField(upload_to='cleaned_files/')),
                ('threats_removed', models.IntegerField(default=0)),
                ('javascript_removed', models.BooleanField(default=False)),
                ('hyperlinks_removed', models.BooleanField(default=False)),
                ('embedded_objects_removed', models.BooleanField(default=False)),
                ('metadata_removed', models.BooleanField(default=False)),
                ('cleaning_time_seconds', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Cleaned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned_versions', to='scanner.filescan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
