# Generated by Django 6.0.7 on 2026-08-03 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_cleanedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanedfile',
            name='cleaned_file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(64), django.core.validators.MaxLengthValidator(64)]),
        ),
    ]
