# Generated by Django 6.0.7 on 2026-07-18 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True, validators=[django.core.validators.URLValidator()])),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('published_date', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='news_cybern_publish_d1bb80_idx'), models.Index(fields=['source'], name='news_cybern_source_c147d8_idx')],
            },
        ),
    ]
