# Generated by Django 6.0.7 on 2026-07-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybernews',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
