# Generated by Django 6.0.7 on 2026-07-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_failed_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
